services:
  server:
    build: .
    pull_policy: build
    restart: unless-stopped
    networks:
      - external-network
    labels:
      traefik.enable: true
      traefik.http.routers.piss.rule: Host(`piss.lenn.rocks`) # set router name and subdomain
      traefik.http.services.piss.loadbalancer.server.port: 80 # set port that is forwarded to internally by treafik (80 is alpine default)


networks:
  external-network:
    external: true # hook into public network instead of creating our own
